osx_image: xcode10.1
language: swift

cache:
- bundler
- cocoapods

install:
- cd Example && bundle install
- pod repo update --silent
- pod install --project-directory=Example

script:
- cd .. && pod lib lint

after_success: 
- cd Example && fastlane test