osx_image: xcode10.2
language: swift
rvm:
- 2.4.5

cache:
- bundler
- cocoapods

before_install:
- cd Example && bundle install && cd ..

install:
- pod install --project-directory=Example

script:
- pod lib lint

after_success: 
- cd Example && bundle exec fastlane test