osx_image: xcode9
language: objective-c

cache:
- bundler
- cocoapods

before_install:
- rvm use $RVM_RUBY_VERSION
- gem install cocoapods
- gem install slather
- gem install coveralls

install:
- pod repo update --silent
- pod install --project-directory=Example
- gem install fastlane -NV

script:
- pod lib lint

after_success: 
- cd Example && fastlane test